List<Map<String, dynamic>> testListIsNow = [
  {
    'isNow': false,
    'hour': '12 AM',
    'degree': 19,
    'label': 30,
    'weatherIcon': 'assets/Moon_cloud_mid_rain32x32.png',
  },
  {
    'isNow': true,
    'hour': 'Now',
    'degree': 19,
    'label': null,
    'weatherIcon': 'assets/Moon_cloud_mid_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': '2 AM',
    'degree': 18,
    'label': null,
    'weatherIcon': 'assets/Moon_cloud_fast_wind32x32.png',
  },
  {
    'isNow': false,
    'hour': '3 AM',
    'degree': 19,
    'label': null,
    'weatherIcon': 'assets/Moon_cloud_mid_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': '4 AM',
    'degree': 19,
    'label': null,
    'weatherIcon': 'assets/Moon_cloud_mid_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': '4 AM',
    'degree': 19,
    'label': null,
    'weatherIcon': 'assets/Sun_cloud_angled_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': '4 AM',
    'degree': 19,
    'label': null,
    'weatherIcon': 'assets/Tornado32x32.png',
  },
];
List<Map<String, dynamic>> testListWeekly = [
  {
    'isNow': false,
    'hour': 'MON',
    'degree': 20,
    'label': 30,
    'weatherIcon': 'assets/Sun_cloud_mid_rain32x32.png',
  },
  {
    'isNow': true,
    'hour': 'TUE',
    'degree': 21,
    'label': null,
    'weatherIcon': 'assets/Sun_cloud_mid_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': 'WENS',
    'degree': 18,
    'label': 100,
    'weatherIcon': 'assets/Sun_cloud_angled_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': 'THU',
    'degree': 20,
    'label': 50,
    'weatherIcon': 'assets/Sun_cloud_angled_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': 'FRI',
    'degree': 22,
    'label': null,
    'weatherIcon': 'assets/Sun_cloud_mid_rain32x32.png',
  },
  {
    'isNow': false,
    'hour': 'SAT',
    'degree': 19,
    'label': 50,
    'weatherIcon': 'assets/Tornado32x32.png',
  },
  {
    'isNow': false,
    'hour': 'SUN',
    'degree': 19,
    'label': null,
    'weatherIcon': 'assets/Tornado32x32.png',
  },
];

List<Map<String, dynamic>> weatherList = [
  {
    'image': 'assets/Moon_cloud_mid_rain.png',
    'indicator': '19°',
    'city': 'Montreal, Canada',
    'expectedRange': 'H:24°  L:18°',
    'weatherDescription': 'Mid Rain',
  },
  {
    'image': 'assets/Moon_cloud_fast_wind.png',
    'indicator': '20°',
    'city': 'Toronto, Canada',
    'expectedRange': 'H:21°  L:-19°',
    'weatherDescription': 'Fast Wind',
  },
  {
    'image': 'assets/Sun_cloud_angled_rain.png',
    'indicator': '13°',
    'city': 'Tokyo, Japan',
    'expectedRange': 'H:16°  L:8°',
    'weatherDescription': 'Showers',
  },
  {
    'image': 'assets/Tornado.png',
    'indicator': '23°',
    'city': 'Tennessee, United States',
    'expectedRange': 'H:26°  L:16°',
    'weatherDescription': 'Tornado',
  },
  {
    'image': 'assets/Moon_cloud_fast_wind.png',
    'indicator': '19°',
    'city': 'Montreal, Canada',
    'expectedRange': 'H:24°  L:18°',
    'weatherDescription': 'Partly Cloudy',
  },
  {
    'image': 'assets/Moon_cloud_fast_wind.png',
    'indicator': '19°',
    'city': 'Montreal, Canada',
    'expectedRange': 'H:24°  L:18°',
    'weatherDescription': 'Partly Cloudy',
  },
];
